replicaCount: 2

image:
  repository: localhost:5000/java-webapp
  # We set a default, but Jenkins will override this dynamically
  tag: "latest" 

service:
  # Using NodePort so we can easily access it on our local laptop browser
  type: NodePort
  port: 8080
  nodePort: 30080